#!/bin/bash
EXPECTED_KERNEL_VERSION="3.13.0-24-generic"
DRIVER="/lib/modules/$(uname -r)/kernel/drivers/net/ethernet/intel/ixgbe/ixgbe.ko"

if [ "$(uname -r)" != "$EXPECTED_KERNEL_VERSION" ]; then
	echo -e "\nERROR!!! THIS PACKAGE ONLY WORKS ON KERNEL $EXPECTED_KERNEL_VERSION\n"
	exit 1
fi
if [ -f "$DRIVER" ]; then
	# if the adallom driver is not installed then backup the official driver
	if [ ! -f "$DRIVER.official" ]; then 
		mv "$DRIVER" "$DRIVER.official"
		echo "Backed up original driver to $DRIVER.official"
	fi
fi
